#-------------------------------
# General Site Settings

title: Magic School Blog
description: We built a robot
email: l.nguyen.paul@gmail.com, change this

menu:
- {name: 'The Bot', url: ''}
- {name: 'Blog', url: 'blog.html'}
#- {name: 'About', url: 'about.html'}
#- {name: 'Contact Us', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Website for robot entry in 2017 UBC Engineering Physics Robot Competition powered by Jekyll and GitHub Pages'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # Magic School Blog

  The website for The Magic School Bot, our entry in the Annual UBC Engineering Physics Summer Robotics Competition.

contact: >
  # Contact

  Amar Shah: [Github](#) [Linkedin](#) [Website](#)


  Cindy Zhang: [Github](#) [Linkedin](#) [Website](#)


  Jason Peng: [Github](#) [Linkedin](#) [Website](#)


  Lise Savard: [Github](#) [Linkedin](#) [Website](#)

#-------------------------------
# Work Section

projects:
- {name: 'The Competition', folder: 'competition', file: 'projects/competition.html'}
- {name: 'Electrical', folder: 'elec', file: 'projects/elec.html'}
- {name: 'Mechanical', folder: 'mech', file: 'projects/mech.html'}
- {name: 'Software', folder: 'software', file: 'projects/software.html'}
- {name: 'Fun', folder: 'fun', file: 'projects/fun.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'https://github.com/WalkervilleElementary'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
